---
title: "naes-04-d"
author: "Ryan Zhang"
date: "10/12/2020"
output: html_document
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = TRUE)

# Read relevant libraries.

library(tidyverse)
library(Hmisc)
library(rqPen)
library(vctrs)
library(foreign)

```


## Reading Data

```{r warning=FALSE}

# Read in the raw data file, cleaning by deleting NAs and only filtering for
# results before January 29, 2008 (since that is the date before Super Tuesday
# primaries).

naes04 <- read.spss("raw_data/naes/naes04-national.sav",
                    to.data.frame = TRUE, use.value.labels = FALSE)
naes04[naes04 == 998] <- NA
naes04[naes04 == 999] <- NA

```


## Cleaning Data

```{r}

df04 <- naes04 %>%

  # Only select columns that correspond to the survey questions that I am
  # interested in, which includes question about favorability, viability,
  # electability, and ideology.
    
  select(cKEY, cRB06, 
         cAB01, cAC04,
         cNA05, cNA03,
         cNA21, cNA15,
         cMA06, 
         cAB27, cAC14,
         cAB02, cAB03, cAB05, cAB07, 
         cAC06, cAC07, cAC09, cAC11,
         )

# Rename columns for ease of data interpretation. 

my_candidate <- c("KERRY","EDWARDS")
my_candidate_id <- as.integer(c(5, 3))

my_names <- c("ID", "voting", 
              "Feeling1", "Feeling2",
              "Viability1", "Viability2",
              "Electability1", "Electability2",
              "Ideology", 
              "Ideology1", "Ideology2", 
              "Cares1", "Inspire1", "Trust1", "Know1",
              "Cares2", "Inspire2", "Trust2", "Know2"
              )

# Also replace numbered survey responses with words, again for ease of
# readability.

colnames(df04) <- my_names

```


```{r}

# Account for viability and electability ratings that are NA.

df04$Viability1 <- ifelse(is.na(df04$Viability1),
                          100 - df04$Viability2, df04$Viability1)
df04$Viability2 <- ifelse(is.na(df04$Viability2),
                          100 - df04$Viability1, df04$Viability2)

df04$Electability1 <- ifelse(is.na(df04$Electability1),
                             100 - df04$Electability2, df04$Electability1)
df04$Electability2 <- ifelse(is.na(df04$Electability2),
                             100 - df04$Electability1, df04$Electability2)

```


```{r}

# Create a new columns that includes a column named VoteCandidate, which
# displays the respondent's ultimate primary pick. This column is needed, since
# it will be the dependent variable in my conditional logistic regression later.

df <- data.frame(my_candidate_id, my_candidate, stringsAsFactors = FALSE)
df04 <-merge(df04, df, by.x = "voting", by.y = "my_candidate_id", all.x = TRUE)
names(df04)[names(df04) == "my_candidate"] <- "VoteCandidate"

```


```{r eval=FALSE, include=FALSE}

# Visually verify that the column renaming and candidate assignments have all
# been correct.

str(df04)

```


## Normalize ratings

```{r warning=FALSE}

# Build a function that normalizes feeling thermometer ratings. 

my_rescale1 <- function(X) { 
  if (max(X, na.rm = TRUE) == min(X, na.rm = TRUE)) 
    X / sum(X, na.rm = TRUE)
  else
    round((X - min(X, na.rm = TRUE)) /
            (max(X, na.rm = TRUE) - min(X, na.rm = TRUE)), 6)
}

# Run feeling thermometer columns (each representing the feeling thermometer
# rating for a different candidate) through the function.

df04[, c("NORMALIZED_FT1", "NORMALIZED_FT2")] <- 
  t(apply(df04[, c("Feeling1", "Feeling2")], MARGIN = 1, FUN = my_rescale1))

# Build a function that normalizes viability and electability ratings. 

my_rescale2 <- function(X) round(X / sum(X, na.rm = TRUE), 6)

# Run viability columns (each representing the viability rating for a different
# candidate) through the function.

df04[, c("NORMALIZED_VIABILITY1", "NORMALIZED_VIABILITY2")] <- 
  t(apply(df04[, c("Viability1", "Viability2")], MARGIN = 1, FUN = my_rescale2))

# Run electability columns (each representing the electability rating for a
# different candidate) through the function.

df04[, c("NORMALIZED_ELECTABILITY1", "NORMALIZED_ELECTABILITY2")] <- 
  t(apply(df04[, c("Electability1", "Electability2")], 
        MARGIN = 1, FUN = my_rescale2))

# Calculate ideological distance according to the formula displayed in my
# ShinyApp. Each column represents the ideological rating for a different
# candidate.

df04[, c("temp_1", "temp_2")] <- square(
  df04[, c("Ideology1", "Ideology2")] - df04[, "Ideology"])

df04 <- df04 %>%
  rowwise() %>%
  mutate(temp_min = min(temp_1, temp_2)) %>%
  mutate(temp_max_min = max(temp_1, temp_2) - min(temp_1, temp_2)) %>%
  mutate(NORMALIZED_IDEOLOGY1 = ifelse(temp_max_min == 0,
                                       ifelse(temp_min == 0, 0, 0.5),
                                       round((temp_1 - temp_min) / 
                                               temp_max_min, 6))) %>%
  mutate(NORMALIZED_IDEOLOGY2 = ifelse(temp_max_min == 0,
                                       ifelse(temp_min == 0, 0, 0.5),
                                       round((temp_2 - temp_min) / 
                                               temp_max_min, 6))) %>%
  select(-starts_with("temp_") )

# Take the average of all the relevant candidate traits. 

df04$TRAITS1 = rowMeans(df04[, c("Cares1", "Inspire1", "Trust1", "Know1")], 
                        na.rm = TRUE) / 10
df04$TRAITS2 = rowMeans(df04[, c("Cares2", "Inspire2", "Trust2", "Know2")], 
                        na.rm = TRUE) / 10

# Convert NANs to NAs, which will eventually be dropped. 

df04[df04 == "NaN"] <- NA

```
 
 
```{r}

# Verify my calculations visually, ensuring that all variables have been
# normalized correctly.

df04[, c("NORMALIZED_FT1", "NORMALIZED_FT2", "Feeling1", "Feeling2")]
df04[, c("NORMALIZED_VIABILITY1", "NORMALIZED_VIABILITY2",  
         "Viability1", "Viability2")]
df04[, c("NORMALIZED_ELECTABILITY1", "NORMALIZED_ELECTABILITY2", 
         "Electability1", "Electability2")]
df04[, c("NORMALIZED_IDEOLOGY1", "NORMALIZED_IDEOLOGY2", "Ideology",
         "Ideology1", "Ideology2")]
df04[, c("TRAITS1", "Cares1", "Inspire1", "Trust1", "Know1")]
df04[, c("TRAITS2", "Cares2", "Inspire2", "Trust2", "Know2")]

```
 
 
## Pivot Data

```{r}

# Pivot my feeling thermometer ratings longer, since conditional logistic
# regressions require multiple rows per respondent (1 row per candidate).

my_cols <- c("ID", "VoteCandidate", "NORMALIZED_FT1", "NORMALIZED_FT2")
df <- df04[, my_cols]
colnames(df) <- c("ID", "VoteCandidate", my_candidate)

df <- df %>%
  pivot_longer(names_to = "Candidate", 
               values_to = "NORMALIZED_FT", 
               cols = -c(ID, VoteCandidate))
df_final <- df

# Pivot my viability ratings longer, since conditional logistic regressions
# require multiple rows per respondent (1 row per candidate).

my_cols <- c("ID", "NORMALIZED_VIABILITY1", "NORMALIZED_VIABILITY2")
df <- df04[, my_cols]
colnames(df) <- c("ID", my_candidate)

df <- df %>%
  pivot_longer(names_to = "Candidate", 
               values_to = "NORMALIZED_VIABILITY", 
               cols = -ID)

# Merge the pivoted viability ratings with the already-pivoted tibble.

df_final = merge(df_final, df, by = c("ID", "Candidate"))

# Convert vote candidate to 0s and 1s, rather than 1s and 2s. 

df_final$VoteCandidate <-  1 * (df_final$Candidate == df_final$VoteCandidate)

# Pivot my electability ratings longer, since conditional logistic regressions
# require multiple rows per respondent (1 row per candidate).

my_cols <- c("ID", "NORMALIZED_ELECTABILITY1", "NORMALIZED_ELECTABILITY2")
df <- df04[, my_cols]
colnames(df) <- c("ID", my_candidate)

df <- df %>%
  pivot_longer(names_to = "Candidate", 
               values_to = "NORMALIZED_ELECTABILITY", 
               cols = -ID)

# Merge the pivoted viability ratings with the already-pivoted tibble.

df_final = merge(df_final, df, by = c("ID", "Candidate"))

# Pivot my ideology ratings longer, since conditional logistic regressions
# require multiple rows per respondent (1 row per candidate).

my_cols <- c("ID", "NORMALIZED_IDEOLOGY1", "NORMALIZED_IDEOLOGY2")
df <- df04[, my_cols]
colnames(df) <- c("ID", my_candidate)

df <- df %>%
  pivot_longer(names_to = "Candidate", 
               values_to = "NORMALIZED_IDEOLOGY", 
               cols = -ID)

# Merge the pivoted viability ratings with the already-pivoted tibble.

df_final = merge(df_final, df, by = c("ID", "Candidate"))

# Pivot my candidate traits ratings longer, since conditional logistic
# regressions require multiple rows per respondent (1 row per candidate).

my_cols <- c("ID", "TRAITS1", "TRAITS2")
df <- df04[, my_cols]
colnames(df) <- c("ID", my_candidate)

df <- df %>%
  pivot_longer(names_to = "Candidate", 
               values_to = "TRAITS", 
               cols = -ID)

# Merge the pivoted viability ratings with the already-pivoted tibble.

df_final = merge(df_final, df, by = c("ID", "Candidate"))

```


```{r}

# Create new columns using candidate names, assigning 0 to all.

df_final[, sort(my_candidate)] <- 0

# Get index when the intersection column name and value match, in order to
# identify the candidate that each respodent voted for.

my_index <- cbind(seq_len(nrow(df_final)), 
                  match(df_final$Candidate, names(df_final)[-1]))

# Assign 1 to my_index cells.

df_final[-1][my_index] <- 1

```


## Write Cleaned Dataset

```{r}

# Write my cleaned dataset for later, when calculating my regressnions.

df_final %>%
  select(-TRAITS) %>%
  drop_na() %>%
  write.dta("clean_data/df04_national_d.dta")

```


## Calculate 4-Part Voter Typology

```{r}

# Write new tibble that determines whether a respondent voted for the candidate
# that he or she viewed most strategically, or for the candidate that he or she
# viewed most sincerely, or both.

df_final_2 <- df_final %>%
  rowwise() %>%
  mutate(SINCERE = NORMALIZED_FT,
         STRATEGIC = (NORMALIZED_VIABILITY + NORMALIZED_ELECTABILITY) / 2) %>%
  select(ID, Candidate, VoteCandidate, SINCERE, STRATEGIC) %>%
  group_by(ID) %>%
  mutate(SINCERE_MAX1 = max(SINCERE),
         STRATEGIC_MAX1 = max(STRATEGIC)) %>%
  mutate(SINCERE_MAX2 = ifelse(SINCERE == SINCERE_MAX1, 1, 0),
         STRATEGIC_MAX2 = ifelse(STRATEGIC == STRATEGIC_MAX1, 1, 0)) %>%
  filter(VoteCandidate == 1) %>%
  drop_na()

```


```{r}

# Write tibble that includes counts, as grouped by year. 

df_final_2 %>%
  group_by(Candidate, SINCERE_MAX2, STRATEGIC_MAX2) %>%
  count() %>%
  group_by(Candidate) %>%
  
  # Convert raw counts into percent, for ease of interpretation.

  mutate(percent = n / sum(n),
         df = "df04_national_d") %>%
  write.csv("/Users/ryan/Google Drive/2020_2021/Thesis/
            Figures/Figure3/df04_national_d_counts.csv")

# Write tibble that includes counts, as grouped by candidate per year. 

df_final_2 %>%
  group_by(SINCERE_MAX2, STRATEGIC_MAX2) %>%
  count() %>%
  group_by() %>%
  
  # Convert raw counts into percent, for ease of interpretation.
  
  mutate(percent = n / sum(n),
         df = "df04_national_d") %>%
  write.csv("/Users/ryan/Google Drive/2020_2021/Thesis/
            Figures/Figure3/df04_national_d_counts_aggregate.csv")

```


## Segment 4-Part Voter Typology by Demographic

```{r}

# Calculate my 4-type voter typology, as segmented by race. 

df_final_2 %>%
  inner_join(naes04, by = c("ID" = "cKEY")) %>%
  group_by(SINCERE_MAX2, STRATEGIC_MAX2, cWC03) %>%
  count() %>%
  
  # Segment respondents by voter type.
  
  mutate(sincere_strategic = case_when(
    (SINCERE_MAX2 == 0 & STRATEGIC_MAX2 == 0) ~ 1,
    (SINCERE_MAX2 == 1 & STRATEGIC_MAX2 == 0) ~ 2,
    (SINCERE_MAX2 == 0 & STRATEGIC_MAX2 == 1) ~ 3,
    (SINCERE_MAX2 == 1 & STRATEGIC_MAX2 == 1) ~ 4,
    )) %>%
  
  # Segment voter type by each race. 
  
  group_by(cWC03) %>%
  mutate(percent = n / sum(n),
         df = "naes04_national",
         race = case_when(
           cWC03 == "1" ~ "WHITE",
           cWC03 == "2" ~ "BLACK",
           cWC03 == "3" ~ "ASIAN",
           cWC03 == "4" ~ "NATIVE",
           cWC03 == "5" ~ "OTHER")) %>%
  write.csv("/Users/ryan/Google Drive/2020_2021/Thesis/
            Figures/Figure10/race/naes04_national_race.csv")

# Calculate my 4-type voter typology, as segmented by education level 

df_final_2 %>%
  inner_join(naes04, by = c("ID" = "cKEY")) %>%
  group_by(SINCERE_MAX2, STRATEGIC_MAX2, cWA03) %>%
  count() %>%
  
  # Segment respondents by voter type.
  
  mutate(sincere_strategic = case_when(
    (SINCERE_MAX2 == 0 & STRATEGIC_MAX2 == 0) ~ 1,
    (SINCERE_MAX2 == 1 & STRATEGIC_MAX2 == 0) ~ 2,
    (SINCERE_MAX2 == 0 & STRATEGIC_MAX2 == 1) ~ 3,
    (SINCERE_MAX2 == 1 & STRATEGIC_MAX2 == 1) ~ 4,
    )) %>%
  group_by(cWA03) %>%
  
  # Segment voter type by each education level.
  
  mutate(percent = n / sum(n),
         df = "naes04_national",
         education = case_when(
           cWA03 == "1" ~ "GRADE8-",
           cWA03 == "2" ~ "SOMEHS",
           cWA03 == "3" ~ "HS",
           cWA03 == "4" ~ "VOCATIONAL",
           cWA03 == "5" ~ "SOMECOLLEGE",
           cWA03 == "6" ~ "ASSOCIATES",
           cWA03 == "7" ~ "BACHELORS",
           cWA03 == "8" ~ "SOMEPROFESSIONAL",
           cWA03 == "9" ~ "PROFESSIONAL")) %>%
  write.csv("/Users/ryan/Google Drive/2020_2021/Thesis/
            Figures/Figure10/education/naes04_national_education.csv")

# Calculate my 4-type voter typology, as segmented by age.

df_final_2 %>%
  inner_join(naes04, by = c("ID" = "cKEY")) %>%
  group_by(SINCERE_MAX2, STRATEGIC_MAX2, cWA02) %>%
  count() %>%
  
  # Segment respondents by voter type.
  
  mutate(sincere_strategic = case_when(
    (SINCERE_MAX2 == 0 & STRATEGIC_MAX2 == 0) ~ 1,
    (SINCERE_MAX2 == 1 & STRATEGIC_MAX2 == 0) ~ 2,
    (SINCERE_MAX2 == 0 & STRATEGIC_MAX2 == 1) ~ 3,
    (SINCERE_MAX2 == 1 & STRATEGIC_MAX2 == 1) ~ 4,
    )) %>%
  group_by(cWA02) %>%
  
  # Segment voter type by each age.
  
  mutate(percent = n / sum(n),
         df = "naes04_national",
         age = cWA02) %>%
  write.csv("/Users/ryan/Google Drive/2020_2021/Thesis/
            Figures/Figure10/age/naes04_national_age.csv")

# Calculate my 4-type voter typology, as segmented by ideology. 

df_final_2 %>%
  inner_join(naes04, by = c("ID" = "cKEY")) %>%
  group_by(SINCERE_MAX2, STRATEGIC_MAX2, cMA06) %>%
  count() %>%
  
  # Segment respondents by voter type.
  
  mutate(sincere_strategic = case_when(
    (SINCERE_MAX2 == 0 & STRATEGIC_MAX2 == 0) ~ 1,
    (SINCERE_MAX2 == 1 & STRATEGIC_MAX2 == 0) ~ 2,
    (SINCERE_MAX2 == 0 & STRATEGIC_MAX2 == 1) ~ 3,
    (SINCERE_MAX2 == 1 & STRATEGIC_MAX2 == 1) ~ 4,
    )) %>%
  group_by(cMA06) %>%
  
  # Segment voter type by ideological identification.
  
  mutate(percent = n / sum(n),
         df = "naes04_national",
         ideology = case_when(
           cMA06 == "1" ~ "VERYCONSERVATIVE",
           cMA06 == "2" ~ "SOMEWHATCONSERVATIVE",
           cMA06 == "3" ~ "MODERATE",
           cMA06 == "4" ~ "SOMEWHATLIBERAL",
           cMA06 == "5" ~ "VERYLIBERAL")) %>%
  write.csv("/Users/ryan/Google Drive/2020_2021/Thesis/
            Figures/Figure10/ideology/naes04_national_ideology.csv")

# Calculate my 4-type voter typology, as segmented by strength of party
# identification.

df_final_2 %>%
  inner_join(naes04, by = c("ID" = "cKEY")) %>%
  group_by(SINCERE_MAX2, STRATEGIC_MAX2, cMA02) %>%
  count() %>%
  
  # Segment respondents by voter type.
  
  mutate(sincere_strategic = case_when(
    (SINCERE_MAX2 == 0 & STRATEGIC_MAX2 == 0) ~ 1,
    (SINCERE_MAX2 == 1 & STRATEGIC_MAX2 == 0) ~ 2,
    (SINCERE_MAX2 == 0 & STRATEGIC_MAX2 == 1) ~ 3,
    (SINCERE_MAX2 == 1 & STRATEGIC_MAX2 == 1) ~ 4,
    )) %>%
  group_by(cMA02) %>%
  
  # Segment voter type by strength of party identification.
  
  mutate(percent = n / sum(n),
         df = "naes04_national",
         party_strength = case_when(
           cMA02 == "1" ~ "STRONG",
           cMA02 == "2" ~ "NOTVERYSTRONG")) %>%
  write.csv("/Users/ryan/Google Drive/2020_2021/Thesis/
            Figures/Figure10/party_strength/naes04_national_party_strength.csv")

# Calculate my 4-type voter typology, as segmented by level of political
# interest.

df_final_2 %>%
  inner_join(naes04, by = c("ID" = "cKEY")) %>%
  group_by(SINCERE_MAX2, STRATEGIC_MAX2, cKA02) %>%
  count() %>%
  
  # Segment respondents by voter type.
  
  mutate(sincere_strategic = case_when(
    (SINCERE_MAX2 == 0 & STRATEGIC_MAX2 == 0) ~ 1,
    (SINCERE_MAX2 == 1 & STRATEGIC_MAX2 == 0) ~ 2,
    (SINCERE_MAX2 == 0 & STRATEGIC_MAX2 == 1) ~ 3,
    (SINCERE_MAX2 == 1 & STRATEGIC_MAX2 == 1) ~ 4,
    )) %>%
  group_by(cKA02) %>%
  
  # Segment voter type by strength of political interest.
  
  mutate(percent = n / sum(n),
         df = "naes04_national",
         political_interest = case_when(
           cKA02 == "1" ~ "VERYCLOSELY",
           cKA02 == "2" ~ "SOMEWHATCLOSELY",
           cKA02 == "3" ~ "NOTTOOCLOSELY",
           cKA02 == "4" ~ "NOTCLOSELYATALL")) %>%
  write.csv("/Users/ryan/Google Drive/2020_2021/Thesis/Figures/Figure10/
            political_interest/naes04_national_political_interest.csv")

# Calculate my 4-type voter typology, as segmented by political efficacy. 

df_final_2 %>%
  inner_join(naes04, by = c("ID" = "cKEY")) %>%
  group_by(SINCERE_MAX2, STRATEGIC_MAX2, cMB11) %>%
  count() %>%
  
  # Segment respondents by voter type.
  
  mutate(sincere_strategic = case_when(
    (SINCERE_MAX2 == 0 & STRATEGIC_MAX2 == 0) ~ 1,
    (SINCERE_MAX2 == 1 & STRATEGIC_MAX2 == 0) ~ 2,
    (SINCERE_MAX2 == 0 & STRATEGIC_MAX2 == 1) ~ 3,
    (SINCERE_MAX2 == 1 & STRATEGIC_MAX2 == 1) ~ 4,
    )) %>%
  group_by(cMB11) %>%
  
  # Segment voter type by level of political efficacy.
  
  mutate(percent = n / sum(n),
         df = "naes04_national",
         efficacy = case_when(
           cMB11 == "1" ~ "STRONGLYAGREE",
           cMB11 == "2" ~ "SOMEWHATAGREE",
           cMB11 == "3" ~ "SOMEWHATDISAGREE",
           cMB11 == "4" ~ "STRONGLYDISAGREE",
           cMB11 == "5" ~ "NEITHER")) %>%
  write.csv("/Users/ryan/Google Drive/2020_2021/Thesis/Figures/Figure10/
            political_efficacy/naes04_national_political_efficacy.csv")

```


```{r include=FALSE}

rm(list = ls())

```

