---
title: "anes"
author: "Ryan Zhang"
date: "10/12/2020"
output: html_document
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = TRUE)

# Read relevant libraries.

library(tidyverse)
library(Hmisc)
library(rqPen)
library(vctrs)
library(foreign)

```


# Read Data

```{r warning=FALSE}

# Read in the raw data file, cleaning by deleting NAs and only filtering for
# results before January 29, 2008 (since that is the date before Super Tuesday
# primaries).

naes00 <- read.spss("raw_data/naes/NAES-2000-Nat-CS-19991214-20000403-Data.sav",
                    to.data.frame = TRUE, use.value.labels = FALSE) %>%
  filter(cdate <= 20000307)
naes00[naes00 == 998] <- NA
naes00[naes00 == 999] <- NA

```


## Clean Data

```{r}

df00 <- naes00 %>%

  # Only select columns that correspond to the survey questions that I am
  # interested in, which includes question about favorability, viability,
  # electability, and ideology.
  
  select(ckey, cr11, 
         ca01, ca21, 
         cn01, cn02, 
         cn06, cn08,
         cv04, 
         ca09, ca28
         )

# Rename columns for ease of data interpretation. 

my_candidate <- c("BUSH", "MCCAIN")
my_candidate_id <- as.integer(c(2, 6))

my_names <- c("ID", "voting", 
              "Feeling1", "Feeling2",
              "Viability1", "Viability2", 
              "Electability1", "Electability2", 
              "Ideology", 
              "Ideology1", "Ideology2"
              )

# Also replace numbered survey responses with words, again for ease of
# readability.

colnames(df00) <- my_names

```


```{r}

# Account for viability and electability ratings that are NA.

df00$Viability1 <- ifelse(is.na(df00$Viability1), 
                          100 - df00$Viability2, df00$Viability1)
df00$Viability2 <- ifelse(is.na(df00$Viability2), 
                          100 - df00$Viability1, df00$Viability2)

df00$Electability1 <- ifelse(is.na(df00$Electability1), 
                             100 - df00$Electability2, df00$Electability1)
df00$Electability2 <- ifelse(is.na(df00$Electability2), 
                             100 - df00$Electability1, df00$Electability2)

```


```{r}

# Create a new columns that includes a column named VoteCandidate, which
# displays the respondent's ultimate primary pick. This column is needed, since
# it will be the dependent variable in my conditional logistic regression later.

df <- data.frame(my_candidate_id, my_candidate, stringsAsFactors = FALSE)
df00 <-merge(df00, df, by.x = "voting", by.y = "my_candidate_id", all.x = TRUE)
names(df00)[names(df00) == "my_candidate"] <- "VoteCandidate"

```


```{r eval=FALSE, include=FALSE}

# Visually verify that the column renaming and candidate assignments have all
# been correct.

str(df00)

```


## Normalize Variables

```{r warning=FALSE}

# Build a function that normalizes feeling thermometer ratings. 

my_rescale1 <- function(X) { 
  if (max(X, na.rm = TRUE) == min(X, na.rm = TRUE)) 
    X / sum(X, na.rm = TRUE)
  else
    round((X - min(X, na.rm = TRUE)) /
            (max(X, na.rm = TRUE) - min(X, na.rm = TRUE)), 6)
}

# Run feeling thermometer columns (each representing the feeling thermometer
# rating for a different candidate) through the function.

df00[, c("NORMALIZED_FT1", "NORMALIZED_FT2")] <- 
  t(apply(df00[, c("Feeling1", "Feeling2")], MARGIN = 1, FUN = my_rescale1))

# Build a function that normalizes viability and electability ratings. 

my_rescale2 <- function(X) round(X / sum(X, na.rm = TRUE), 6)

# Run viability columns (each representing the viability rating for a different
# candidate) through the function.

df00[, c("NORMALIZED_VIABILITY1", "NORMALIZED_VIABILITY2")] <- 
  t(apply(df00[, c("Viability1", "Viability2")], MARGIN = 1, FUN = my_rescale2))

# Run electability columns (each representing the electability rating for a
# different candidate) through the function.

df00[, c("NORMALIZED_ELECTABILITY1", "NORMALIZED_ELECTABILITY2")] <- 
  t(apply(df00[, c("Electability1", "Electability2")], 
          MARGIN = 1, FUN = my_rescale2))

# Calculate ideological distance according to the formula displayed in my
# ShinyApp. Each column represents the ideological rating for a different
# candidate.

df00[, c("temp_1", "temp_2")] <- 
  square(df00[, c("Ideology1", "Ideology2")] - df00[, "Ideology"])

df00 <- df00 %>%
  rowwise() %>%
  mutate(temp_min = min(temp_1, temp_2)) %>%
  mutate(temp_max_min = max(temp_1, temp_2) - min(temp_1, temp_2)) %>%
  mutate(NORMALIZED_IDEOLOGY1 = ifelse(temp_max_min == 0,
                                       ifelse(temp_min == 0, 0, 0.5),
                                       round((temp_1 - temp_min) / 
                                               temp_max_min, 6))) %>%
  mutate(NORMALIZED_IDEOLOGY2 = ifelse(temp_max_min == 0,
                                       ifelse(temp_min == 0, 0, 0.5),
                                       round((temp_2 - temp_min) / 
                                               temp_max_min, 6))) %>%
  select(-starts_with("temp_") )

# Convert NANs to NAs, which will eventually be dropped. 

df00[df00 == "NaN"] <- NA

```
 
 
```{r}

# Verify my calculations visually, ensuring that all variables have been
# normalized correctly.

df00[, c("NORMALIZED_FT1", "NORMALIZED_FT2", "Feeling1", "Feeling2")]
df00[, c("NORMALIZED_VIABILITY1", "NORMALIZED_VIABILITY2", 
         "Viability1", "Viability2")]
df00[, c("NORMALIZED_ELECTABILITY1", "NORMALIZED_ELECTABILITY2", 
         "Electability1", "Electability2")]
df00[, c("NORMALIZED_IDEOLOGY1", "NORMALIZED_IDEOLOGY2", 
         "Ideology1", "Ideology2")]

```
 
 
## Pivot Data

```{r}

# Pivot my feeling thermometer ratings longer, since conditional logistic
# regressions require multiple rows per respondent (1 row per candidate).

my_cols <- c("ID", "VoteCandidate", "NORMALIZED_FT1", "NORMALIZED_FT2")
df <- df00[, my_cols]
colnames(df) <- c("ID", "VoteCandidate", my_candidate)

df <- df %>%
  pivot_longer(names_to = "Candidate", 
               values_to = "NORMALIZED_FT", 
               cols = -c(ID, VoteCandidate))
df_final <- df

# Pivot my viability ratings longer, since conditional logistic regressions
# require multiple rows per respondent (1 row per candidate).

my_cols <- c("ID", "NORMALIZED_VIABILITY1", "NORMALIZED_VIABILITY2")
df <- df00[, my_cols]
colnames(df) <- c("ID", my_candidate)

df <- df %>%
  pivot_longer(names_to = "Candidate", 
               values_to = "NORMALIZED_VIABILITY", 
               cols = -ID)

# Merge the pivoted viability ratings with the already-pivoted tibble.

df_final = merge(df_final, df, by = c("ID", "Candidate"))

# Convert vote candidate to 0s and 1s, rather than 1s and 2s. 

df_final$VoteCandidate <-  1 * (df_final$Candidate == df_final$VoteCandidate)

# Pivot my electability ratings longer, since conditional logistic regressions
# require multiple rows per respondent (1 row per candidate).

my_cols <- c("ID", "NORMALIZED_ELECTABILITY1", "NORMALIZED_ELECTABILITY2")
df <- df00[, my_cols]
colnames(df) <- c("ID", my_candidate)

df <- df %>%
  pivot_longer(names_to = "Candidate", 
               values_to = "NORMALIZED_ELECTABILITY", 
               cols = -ID)

# Merge the pivoted viability ratings with the already-pivoted tibble.

df_final = merge(df_final, df, by = c("ID", "Candidate"))

# Pivot my ideology ratings longer, since conditional logistic regressions
# require multiple rows per respondent (1 row per candidate).

my_cols <- c("ID", "NORMALIZED_IDEOLOGY1", "NORMALIZED_IDEOLOGY2")
df <- df00[, my_cols]
colnames(df) <- c("ID", my_candidate)

df <- df %>%
  pivot_longer(names_to = "Candidate", 
               values_to = "NORMALIZED_IDEOLOGY", 
               cols = -ID)

# Merge the pivoted ideology ratings with the already-pivoted tibble.

df_final = merge(df_final, df, by = c("ID", "Candidate"))

```


```{r}

# Create new columns using candidate names, assigning 0 to all.

df_final[, sort(my_candidate)] <- 0

# Get index when the intersection column name and value match, in order to
# identify the candidate that each respodent voted for.

my_index <- cbind(seq_len(nrow(df_final)), 
                  match(df_final$Candidate, names(df_final)[-1]))

# Assign 1 to my_index cells.

df_final[-1][my_index] <- 1

```


## Write Cleaned Dataset

```{r}

# Write my cleaned dataset for later use, when calculating my regressnions.

df_final %>%
  drop_na() %>%
  write.dta("clean_data/df00_national_r.dta")

```


# Calculate 4-Part Voter Typology

```{r}

# Write new tibble that determines whether a respondent voted for the candidate
# that he or she viewed most strategically, or for the candidate that he or she
# viewed most sincerely, or both.

df_final_2 <- df_final %>%
  rowwise() %>%
  mutate(SINCERE = NORMALIZED_FT,
         STRATEGIC = (NORMALIZED_VIABILITY + NORMALIZED_ELECTABILITY) / 2) %>%
  select(ID, Candidate, VoteCandidate, SINCERE, STRATEGIC) %>%
  group_by(ID) %>%
  mutate(SINCERE_MAX1 = max(SINCERE),
         STRATEGIC_MAX1 = max(STRATEGIC)) %>%
  mutate(SINCERE_MAX2 = ifelse(SINCERE == SINCERE_MAX1, 1, 0),
         STRATEGIC_MAX2 = ifelse(STRATEGIC == STRATEGIC_MAX1, 1, 0)) %>%
  filter(VoteCandidate == 1) %>%
  drop_na()

```


```{r}

# Write tibble that includes counts, as grouped by year. 

df_final_2 %>%
  group_by(Candidate, SINCERE_MAX2, STRATEGIC_MAX2) %>%
  count() %>%
  group_by(Candidate) %>%
  
  # Convert raw counts into percent, for ease of interpretation.
  
  mutate(percent = n / sum(n),
         df = "df00_national_r") %>%
  write.csv("/Users/ryan/Google Drive/2020_2021/Thesis/
            Figures/Figure3/df00_national_r_counts.csv")

# Write tibble that includes counts, as grouped by candidate per year. 

df_final_2 %>%
  group_by(SINCERE_MAX2, STRATEGIC_MAX2) %>%
  count() %>%
  group_by() %>%
  
  # Convert raw counts into percent, for ease of interpretation.
  
  mutate(percent = n / sum(n),
         df = "df00_national_r") %>%
  write.csv("/Users/ryan/Google Drive/2020_2021/Thesis/
            Figures/Figure3/df00_national_r_counts_aggregate.csv")

```


## Segment 4-Part Voter Typology by Demographic

```{r}

# Calculate my 4-type voter typology, as segmented by race. 

df_final_2 %>%
  inner_join(naes00, by = c("ID" = "ckey")) %>%
  group_by(SINCERE_MAX2, STRATEGIC_MAX2, cw03) %>%
  count() %>%
  
  # Segment respondents by voter type.
  
  mutate(sincere_strategic = case_when(
    (SINCERE_MAX2 == 0 & STRATEGIC_MAX2 == 0) ~ 1,
    (SINCERE_MAX2 == 1 & STRATEGIC_MAX2 == 0) ~ 2,
    (SINCERE_MAX2 == 0 & STRATEGIC_MAX2 == 1) ~ 3,
    (SINCERE_MAX2 == 1 & STRATEGIC_MAX2 == 1) ~ 4,
    )) %>%
  group_by(cw03) %>%
  
  # Segment voter type by each race. 
  
  mutate(percent = n / sum(n),
         df = "naes00_national_r",
         race = case_when(
           cw03 == "1" ~ "WHITE",
           cw03 == "2" ~ "BLACK",
           cw03 == "3" ~ "ASIAN",
           cw03 == "4" ~ "OTHER")) %>%
  write.csv("/Users/ryan/Google Drive/2020_2021/Thesis/
            Figures/Figure10/race/naes00_national_r_race.csv")

# Calculate my 4-type voter typology, as segmented by education level 

df_final_2 %>%
  inner_join(naes00, by = c("ID" = "ckey")) %>%
  group_by(SINCERE_MAX2, STRATEGIC_MAX2, cw06) %>%
  count() %>%
  
  # Segment respondents by voter type.
  
  mutate(sincere_strategic = case_when(
    (SINCERE_MAX2 == 0 & STRATEGIC_MAX2 == 0) ~ 1,
    (SINCERE_MAX2 == 1 & STRATEGIC_MAX2 == 0) ~ 2,
    (SINCERE_MAX2 == 0 & STRATEGIC_MAX2 == 1) ~ 3,
    (SINCERE_MAX2 == 1 & STRATEGIC_MAX2 == 1) ~ 4,
    )) %>%
  group_by(cw06) %>%
  
  # Segment voter type by each education level.
  
  mutate(percent = n / sum(n),
         df = "naes00_national_r",
         education = case_when(
           cw06 == "1" ~ "GRADE8-",
           cw06 == "2" ~ "SOMEHS",
           cw06 == "3" ~ "HS",
           cw06 == "4" ~ "VOCATIONAL",
           cw06 == "5" ~ "SOMECOLLEGE",
           cw06 == "6" ~ "ASSOCIATES",
           cw06 == "7" ~ "BACHELORS",
           cw06 == "8" ~ "SOMEPROFESSIONAL",
           cw06 == "9" ~ "PROFESSIONAL")) %>%
  write.csv("/Users/ryan/Google Drive/2020_2021/Thesis/
            Figures/Figure10/education/naes00_national_r_education.csv")

# Calculate my 4-type voter typology, as segmented by age.

df_final_2 %>%
  inner_join(naes00, by = c("ID" = "ckey")) %>%
  group_by(SINCERE_MAX2, STRATEGIC_MAX2, cw02) %>%
  count() %>%
  
  # Segment respondents by voter type.
  
  mutate(sincere_strategic = case_when(
    (SINCERE_MAX2 == 0 & STRATEGIC_MAX2 == 0) ~ 1,
    (SINCERE_MAX2 == 1 & STRATEGIC_MAX2 == 0) ~ 2,
    (SINCERE_MAX2 == 0 & STRATEGIC_MAX2 == 1) ~ 3,
    (SINCERE_MAX2 == 1 & STRATEGIC_MAX2 == 1) ~ 4,
    )) %>%
  group_by(cw02) %>%
  
  # Segment voter type by each age.
  
  mutate(percent = n / sum(n),
         df = "naes00_national_r",
         age = cw02) %>%
  write.csv("/Users/ryan/Google Drive/2020_2021/Thesis/
            Figures/Figure10/age/naes00_national_r_age.csv")

# Calculate my 4-type voter typology, as segmented by ideology. 

df_final_2 %>%
  inner_join(naes00, by = c("ID" = "ckey")) %>%
  group_by(SINCERE_MAX2, STRATEGIC_MAX2, cv04) %>%
  count() %>%
  
  # Segment respondents by voter type.
  
  mutate(sincere_strategic = case_when(
    (SINCERE_MAX2 == 0 & STRATEGIC_MAX2 == 0) ~ 1,
    (SINCERE_MAX2 == 1 & STRATEGIC_MAX2 == 0) ~ 2,
    (SINCERE_MAX2 == 0 & STRATEGIC_MAX2 == 1) ~ 3,
    (SINCERE_MAX2 == 1 & STRATEGIC_MAX2 == 1) ~ 4,
    )) %>%
  group_by(cv04) %>%
  
  # Segment voter type by ideological identification.
  
  mutate(percent = n / sum(n),
         df = "naes00_national_r",
         ideology = case_when(
           cv04 == "1" ~ "VERYCONSERVATIVE",
           cv04 == "2" ~ "SOMEWHATCONSERVATIVE",
           cv04 == "3" ~ "MODERATE",
           cv04 == "4" ~ "SOMEWHATLIBERAL",
           cv04 == "5" ~ "VERYLIBERAL")) %>%
  write.csv("/Users/ryan/Google Drive/2020_2021/Thesis/
            Figures/Figure10/ideology/naes00_national_r_ideology.csv")

# Calculate my 4-type voter typology, as segmented by strength of party
# identification.

df_final_2 %>%
  inner_join(naes00, by = c("ID" = "ckey")) %>%
  group_by(SINCERE_MAX2, STRATEGIC_MAX2, cv02) %>%
  count() %>%
  
  # Segment respondents by voter type.
  
  mutate(sincere_strategic = case_when(
    (SINCERE_MAX2 == 0 & STRATEGIC_MAX2 == 0) ~ 1,
    (SINCERE_MAX2 == 1 & STRATEGIC_MAX2 == 0) ~ 2,
    (SINCERE_MAX2 == 0 & STRATEGIC_MAX2 == 1) ~ 3,
    (SINCERE_MAX2 == 1 & STRATEGIC_MAX2 == 1) ~ 4,
    )) %>%
  group_by(cv02) %>%
  
  # Segment voter type by strength of party identification.
  
  mutate(percent = n / sum(n),
         df = "naes00_national_r",
         party_strength = case_when(
           cv02 == "1" ~ "STRONG",
           cv02 == "2" ~ "NOTVERYSTRONG")) %>%
  write.csv("/Users/ryan/Google Drive/2020_2021/Thesis/Figures/Figure10/
            party_strength/naes00_national_r_party_strength.csv")

# Calculate my 4-type voter typology, as segmented by level of political
# interest.

df_final_2 %>%
  inner_join(naes00, by = c("ID" = "ckey")) %>%
  group_by(SINCERE_MAX2, STRATEGIC_MAX2, ck02) %>%
  count() %>%
  
  # Segment respondents by voter type.
  
  mutate(sincere_strategic = case_when(
    (SINCERE_MAX2 == 0 & STRATEGIC_MAX2 == 0) ~ 1,
    (SINCERE_MAX2 == 1 & STRATEGIC_MAX2 == 0) ~ 2,
    (SINCERE_MAX2 == 0 & STRATEGIC_MAX2 == 1) ~ 3,
    (SINCERE_MAX2 == 1 & STRATEGIC_MAX2 == 1) ~ 4,
    )) %>%
  group_by(ck02) %>%
  
  # Segment voter type by strength of political interest.
  
  mutate(percent = n / sum(n),
         df = "naes00_national_r",
         political_interest = case_when(
           ck02 == "1" ~ "VERYCLOSELY",
           ck02 == "2" ~ "SOMEWHATCLOSELY",
           ck02 == "3" ~ "NOTTOOCLOSELY")) %>%
  # I took out 4!
  write.csv("/Users/ryan/Google Drive/2020_2021/Thesis/Figures/Figure10/
            political_interest/naes00_national_r_political_interest.csv")

# Calculate my 4-type voter typology, as segmented by political efficacy. 

df_final_2 %>%
  inner_join(naes00, by = c("ID" = "ckey")) %>%
  group_by(SINCERE_MAX2, STRATEGIC_MAX2, cm16) %>%
  count() %>%
  
  # Segment respondents by voter type.
  
  mutate(sincere_strategic = case_when(
    (SINCERE_MAX2 == 0 & STRATEGIC_MAX2 == 0) ~ 1,
    (SINCERE_MAX2 == 1 & STRATEGIC_MAX2 == 0) ~ 2,
    (SINCERE_MAX2 == 0 & STRATEGIC_MAX2 == 1) ~ 3,
    (SINCERE_MAX2 == 1 & STRATEGIC_MAX2 == 1) ~ 4,
    )) %>%
  group_by(cm16) %>%
  
  # Segment voter type by level of political efficacy.
  
  mutate(percent = n / sum(n),
         df = "naes00_national_r",
         efficacy = case_when(
           cm16 == "1" ~ "STRONGLYAGREE",
           cm16 == "2" ~ "SOMEWHATAGREE",
           cm16 == "3" ~ "SOMEWHATDISAGREE",
           cm16 == "4" ~ "STRONGLYDISAGREE")) %>%
  write.csv("/Users/ryan/Google Drive/2020_2021/Thesis/Figures/Figure10/
            political_efficacy/naes00_national_r_political_efficacy.csv")

```


```{r include=FALSE}

rm(list = ls())

```

