---
title: "anes"
author: "Ryan Zhang"
date: "10/12/2020"
output: html_document
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = TRUE)

# Read relevant libraries.

library(tidyverse)
library(Hmisc)
library(rqPen)
library(vctrs)
library(foreign)
library(dplyr)

```


## Read Data

```{r warning=FALSE}

# Read in the raw data file, cleaning by deleting NAs and only filtering for
# results before January 29, 2008 (since that is the date before Super Tuesday
# primaries).

naes08_phone <- read.spss("raw_data/naes/naes08-phone-nat-rcs-data-full.sav",
                  to.data.frame = TRUE, use.value.labels = FALSE) %>%
  filter(DATE_c <= 20080129)
naes08_phone[naes08_phone == 998] <- NA
naes08_phone[naes08_phone == 999] <- NA

```


## Clean Data

```{r}

df08phone <- naes08_phone %>%

  # Only select columns that correspond to the survey questions that I am
  # interested in, which includes question about favorability, viability,
  # electability, and ideology.

  select(RKEY, RBa02_c, 
         ABc01_c, ABe01_c, ABo01_c,
         NAa06_c, NAa07_c, NAa08_c,
         NBa05_c, NBa06_c, NBa07_c,
         MA04_c, 
         ABc03_c, ABe02_c, ABo04_c,
         ABc04_c, ABc05_c, ABc06_c, ABc07_c, 
         ABe03_c, ABe04_c, ABe05_c, ABe06_c, 
         ABo05_c, ABo06_c, ABo07_c, ABo08_c,
         )

# Rename columns for ease of data interpretation. 

my_candidate <- c("CLINTON","EDWARDS","OBAMA")
my_candidate_id <- as.integer(c(2, 4, 7))

my_names <- c("ID", "voting", 
              "Feeling1", "Feeling2", "Feeling3",
              "Viability1", "Viability2", "Viability3",
              "Electability1", "Electability2", "Electability3",
              "Ideology", 
              "Ideology1", "Ideology2", "Ideology3", 
              "Lead1", "Trust1", "Experience1", "Judgement1",
              "Lead2", "Trust2", "Experience2", "Judgement2",
              "Lead3", "Trust3", "Experience3", "Judgement3"
              )

# Also replace numbered survey responses with words, again for ease of
# readability.

colnames(df08phone) <- my_names

```


```{r}

# Create a new columns that includes a column named VoteCandidate, which
# displays the respondent's ultimate primary pick. This column is needed, since
# it will be the dependent variable in my conditional logistic regression later.

df <- data.frame(my_candidate_id, my_candidate, stringsAsFactors = FALSE)
df08phone <-merge(df08phone, df, by.x = "voting", 
                  by.y = "my_candidate_id", all.x = TRUE)
names(df08phone)[names(df08phone) == "my_candidate"] <- "VoteCandidate"

```


```{r eval=FALSE, include=FALSE}

# Visually verify that the column renaming and candidate assignments have all
# been correct.

str(df08phone)

```


## Normalize Variables

```{r warning=FALSE}

# Build a function that normalizes feeling thermometer ratings. 

my_rescale1 <- function(X) { 
  if (max(X, na.rm = TRUE) == min(X, na.rm = TRUE)) 
    X / sum(X, na.rm = TRUE)
  else
    round((X - min(X, na.rm = TRUE)) /
            (max(X, na.rm = TRUE) - min(X, na.rm = TRUE)), 6)
}

# Run feeling thermometer columns (each representing the feeling thermometer
# rating for a different candidate) through the function.

df08phone[, c("NORMALIZED_FT1", "NORMALIZED_FT2", "NORMALIZED_FT3")] <- 
  t(apply(df08phone[, c("Feeling1", "Feeling2", "Feeling3")], MARGIN = 1,
          FUN = my_rescale1))

# Build a function that normalizes viability and electability ratings. 

my_rescale2 <- function(X) round(X / sum(X, na.rm = TRUE), 6)

# Run viability columns (each representing the viability rating for a different
# candidate) through the function.

df08phone[, c("NORMALIZED_VIABILITY1", "NORMALIZED_VIABILITY2",
              "NORMALIZED_VIABILITY3")] <- t(apply(
                df08phone[, c("Viability1", "Viability2", "Viability3")],
                MARGIN = 1, FUN = my_rescale2))

# Run electability columns (each representing the electability rating for a
# different candidate) through the function.

df08phone[, c("NORMALIZED_ELECTABILITY1", "NORMALIZED_ELECTABILITY2",
              "NORMALIZED_ELECTABILITY3")] <- t(apply(
                df08phone[, c("Electability1", "Electability2",
                              "Electability3")],
                MARGIN = 1, FUN = my_rescale2))

# Calculate ideological distance according to the formula displayed in my
# ShinyApp. Each column represents the ideological rating for a different
# candidate.

df08phone[, c("temp_1", "temp_2", "temp_3")] <- square(
  df08phone[, c("Ideology1", "Ideology2", "Ideology3")] -
    df08phone[, "Ideology"])

df08phone <- df08phone %>%
  rowwise() %>%
  mutate(temp_min = min(temp_1, temp_2, temp_3)) %>%
  mutate(temp_max_min = max(temp_1, temp_2, temp_3) -
           min(temp_1, temp_2, temp_3)) %>%
  mutate(NORMALIZED_IDEOLOGY1 = ifelse(temp_max_min == 0,
                                       ifelse(temp_min == 0, 0, 0.5),
                                       round((temp_1 - temp_min) / 
                                               temp_max_min, 6))) %>%
  mutate(NORMALIZED_IDEOLOGY2 = ifelse(temp_max_min == 0,
                                       ifelse(temp_min == 0, 0, 0.5),
                                       round((temp_2 - temp_min) / 
                                               temp_max_min, 6))) %>%
  mutate(NORMALIZED_IDEOLOGY3 = ifelse(temp_max_min == 0,
                                       ifelse(temp_min == 0, 0, 0.5),
                                       round((temp_3 - temp_min) / 
                                               temp_max_min, 6))) %>%
  select(-starts_with("temp_"))

# Take the average of all the relevant candidate traits. 

df08phone$TRAITS1 = rowMeans(
  df08phone[, c("Lead1", "Trust1", "Experience1", "Judgement1")],
  na.rm = TRUE) / 10
df08phone$TRAITS2 = rowMeans(
  df08phone[, c("Lead2", "Trust2", "Experience2", "Judgement2")],
  na.rm = TRUE) / 10
df08phone$TRAITS3 = rowMeans(
  df08phone[, c("Lead3", "Trust3", "Experience3", "Judgement3")],
  na.rm = TRUE) / 10

# Convert NANs to NAs, which will eventually be dropped. 

df08phone[df08phone == "NaN"] <- NA

```
 
 
```{r}

# Verify my calculations visually, ensuring that all variables have been
# normalized correctly.

df08phone[, c("NORMALIZED_FT1", "NORMALIZED_FT2", "NORMALIZED_FT3", 
              "Feeling1", "Feeling2", "Feeling3")]
df08phone[, c("NORMALIZED_VIABILITY1", "NORMALIZED_VIABILITY2", 
              "NORMALIZED_VIABILITY3", "Viability1", "Viability2", 
              "Viability3")]
df08phone[, c("NORMALIZED_ELECTABILITY1", "NORMALIZED_ELECTABILITY2", 
              "NORMALIZED_ELECTABILITY3", "Electability1", "Electability2", 
              "Electability3")]
df08phone[, c("NORMALIZED_IDEOLOGY1", "NORMALIZED_IDEOLOGY2",
              "NORMALIZED_IDEOLOGY3", "Ideology",
              "Ideology1", "Ideology2", "Ideology3")]
df08phone[, c("TRAITS1", "Lead1", "Trust1", "Experience1", "Judgement1")]
df08phone[, c("TRAITS2", "Lead2", "Trust2", "Experience2", "Judgement2")]
df08phone[, c("TRAITS3", "Lead3", "Trust3", "Experience3", "Judgement3")]

```
 

## Pivot Data

```{r}

# Pivot my feeling thermometer ratings longer, since conditional logistic
# regressions require multiple rows per respondent (1 row per candidate).

my_cols <- c("ID", "VoteCandidate", "NORMALIZED_FT1", "NORMALIZED_FT2",
             "NORMALIZED_FT3")
df <- df08phone[, my_cols]
colnames(df) <- c("ID", "VoteCandidate", my_candidate)

df <- df %>%
  pivot_longer(names_to = "Candidate", 
               values_to = "NORMALIZED_FT", 
               cols = -c(ID, VoteCandidate))
df_final <- df

# Pivot my viability ratings longer, since conditional logistic regressions
# require multiple rows per respondent (1 row per candidate).

my_cols <- c("ID", "NORMALIZED_VIABILITY1", "NORMALIZED_VIABILITY2",
             "NORMALIZED_VIABILITY3")
df <- df08phone[, my_cols]
colnames(df) <- c("ID", my_candidate)

df <- df %>%
  pivot_longer(names_to = "Candidate", 
               values_to = "NORMALIZED_VIABILITY", 
               cols = -ID)

# Merge the pivoted viability ratings with the already-pivoted tibble.

df_final = merge(df_final, df, by = c("ID", "Candidate"))

# Convert vote candidate to 0s and 1s, rather than 1s and 2s. 

df_final$VoteCandidate <- 1 * (df_final$Candidate == df_final$VoteCandidate)

# Pivot my electability ratings longer, since conditional logistic regressions
# require multiple rows per respondent (1 row per candidate).

my_cols <- c("ID", "NORMALIZED_ELECTABILITY1", "NORMALIZED_ELECTABILITY2",
             "NORMALIZED_ELECTABILITY3")
df <- df08phone[, my_cols]
colnames(df) <- c("ID", my_candidate)

df <- df %>%
  pivot_longer(names_to = "Candidate", 
               values_to = "NORMALIZED_ELECTABILITY", 
               cols = -ID)

# Merge the pivoted viability ratings with the already-pivoted tibble.

df_final = merge(df_final, df, by = c("ID", "Candidate"))

# Pivot my ideology ratings longer, since conditional logistic regressions
# require multiple rows per respondent (1 row per candidate).

my_cols <- c("ID", "NORMALIZED_IDEOLOGY1", "NORMALIZED_IDEOLOGY2",
             "NORMALIZED_IDEOLOGY3")
df <- df08phone[, my_cols]
colnames(df) <- c("ID", my_candidate)

df <- df %>%
  pivot_longer(names_to = "Candidate", 
               values_to = "NORMALIZED_IDEOLOGY", 
               cols = -ID)

# Merge the pivoted ideology ratings with the already-pivoted tibble.

df_final = merge(df_final, df, by = c("ID", "Candidate"))

# Pivot my candidate traits ratings longer, since conditional logistic
# regressions require multiple rows per respondent (1 row per candidate).

my_cols <- c("ID", "TRAITS1", "TRAITS2", "TRAITS3")
df <- df08phone[, my_cols]
colnames(df) <- c("ID", my_candidate)

df <- df %>%
  pivot_longer(names_to = "Candidate", 
               values_to = "TRAITS", 
               cols = -ID)

# Merge the pivoted character traits ratings with the already-pivoted tibble.

df_final = merge(df_final, df, by = c("ID", "Candidate"))

```


```{r}

# Create new columns using candidate names, assigning 0 to all.

df_final[, sort(my_candidate)] <- 0

# Get index when the intersection column name and value match, in order to
# identify the candidate that each respodent voted for.

my_index <- cbind(seq_len(nrow(df_final)), 
                  match(df_final$Candidate, names(df_final)[-1]))

# Assign 1 to my_index cells.

df_final[-1][my_index] <- 1

```


## Write Cleaned Dataset

```{r}

# Write my cleaned dataset for later use, when calculating my regressnions.

df_final %>%
  drop_na() %>%
  write.dta("clean_data/df08phone_d.dta")

```


## Calculate 4-Part Voter Typology

```{r}

# Write new tibble that determines whether a respondent voted for the candidate
# that he or she viewed most strategically, or for the candidate that he or she
# viewed most sincerely, or both.

df_final_2 <- df_final %>%
  rowwise() %>%
  mutate(SINCERE = (NORMALIZED_FT + TRAITS) / 2,
         STRATEGIC = (NORMALIZED_VIABILITY + NORMALIZED_ELECTABILITY) / 2) %>%
  select(ID, Candidate, VoteCandidate, SINCERE, STRATEGIC) %>%
  group_by(ID) %>%
  mutate(SINCERE_MAX1 = max(SINCERE),
         STRATEGIC_MAX1 = max(STRATEGIC)) %>%
  mutate(SINCERE_MAX2 = ifelse(SINCERE == SINCERE_MAX1, 1, 0),
         STRATEGIC_MAX2 = ifelse(STRATEGIC == STRATEGIC_MAX1, 1, 0)) %>%
  filter(VoteCandidate == 1) %>%
  drop_na()

```


```{r}

# Write tibble that includes counts, as grouped by year. 

df_final_2 %>%
  group_by(Candidate, SINCERE_MAX2, STRATEGIC_MAX2) %>%
  count() %>%
  group_by(Candidate) %>%
  
  # Convert raw counts into percent, for ease of interpretation.
  
  mutate(percent = n / sum(n),
         df = "df08phone_d") %>%
  write.csv("/Users/ryan/Google Drive/2020_2021/Thesis/
            Figures/Figure3/df08phone_d_counts.csv")

# Write tibble that includes counts, as grouped by candidate per year. 

df_final_2 %>%
  group_by(SINCERE_MAX2, STRATEGIC_MAX2) %>%
  count() %>%
  group_by() %>%

  # Convert raw counts into percent, for ease of interpretation.
  
  mutate(percent = n / sum(n),
         df = "df08phone_d") %>%
  write.csv("/Users/ryan/Google Drive/2020_2021/Thesis/
            Figures/Figure3/df08phone_d_counts_aggregate.csv")

```


## Segment 4-Part Voter Typology by Demographic

```{r}

# Calculate my 4-type voter typology, as segmented by race. 

df_final_2 %>%
  inner_join(naes08_phone, by = c("ID" = "RKEY")) %>%
  group_by(SINCERE_MAX2, STRATEGIC_MAX2, WC03_c) %>%
  count() %>%
  
  # Segment respondents by voter type.
  
  mutate(sincere_strategic = case_when(
    (SINCERE_MAX2 == 0 & STRATEGIC_MAX2 == 0) ~ 1,
    (SINCERE_MAX2 == 1 & STRATEGIC_MAX2 == 0) ~ 2,
    (SINCERE_MAX2 == 0 & STRATEGIC_MAX2 == 1) ~ 3,
    (SINCERE_MAX2 == 1 & STRATEGIC_MAX2 == 1) ~ 4,
    )) %>%
  group_by(WC03_c) %>%
  
  # Segment voter type by each race. 
  
  mutate(percent = n / sum(n),
         df = "naes08_phone_d",
         race = case_when(
           WC03_c == "1" ~ "WHITE",
           WC03_c == "2" ~ "BLACK",
           WC03_c == "3" ~ "ASIAN",
           WC03_c == "4" ~ "NATIVE",
           WC03_c == "5" ~ "HISPANIC",
           WC03_c == "6" ~ "MIXED",
           WC03_c == "7" ~ "OTHER")) %>%
  write.csv("/Users/ryan/Google Drive/2020_2021/Thesis/
            Figures/Figure10/race/naes08_phone_d_race.csv")

# Calculate my 4-type voter typology, as segmented by education level 

df_final_2 %>%
  inner_join(naes08_phone, by = c("ID" = "RKEY")) %>%
  group_by(SINCERE_MAX2, STRATEGIC_MAX2, WA03_c) %>%
  count() %>%
  
  # Segment respondents by voter type.

  mutate(sincere_strategic = case_when(
    (SINCERE_MAX2 == 0 & STRATEGIC_MAX2 == 0) ~ 1,
    (SINCERE_MAX2 == 1 & STRATEGIC_MAX2 == 0) ~ 2,
    (SINCERE_MAX2 == 0 & STRATEGIC_MAX2 == 1) ~ 3,
    (SINCERE_MAX2 == 1 & STRATEGIC_MAX2 == 1) ~ 4,
    )) %>%
  group_by(WA03_c) %>%
  
  # Segment voter type by each education level.
  
  mutate(percent = n / sum(n),
         df = "naes08_phone_d",
         education = case_when(
           WA03_c == "1" ~ "GRADE8-",
           WA03_c == "2" ~ "SOMEHS",
           WA03_c == "3" ~ "HS",
           WA03_c == "4" ~ "VOCATIONAL",
           WA03_c == "5" ~ "SOMECOLLEGE",
           WA03_c == "6" ~ "ASSOCIATES",
           WA03_c == "7" ~ "BACHELORS",
           WA03_c == "8" ~ "SOMEPROFESSIONAL",
           WA03_c == "9" ~ "PROFESSIONAL")) %>%
  write.csv("/Users/ryan/Google Drive/2020_2021/Thesis/
            Figures/Figure10/education/naes08_phone_d_education.csv")

# Calculate my 4-type voter typology, as segmented by age.

df_final_2 %>%
  inner_join(naes08_phone, by = c("ID" = "RKEY")) %>%
  group_by(SINCERE_MAX2, STRATEGIC_MAX2, WA02_c) %>%
  count() %>%
  
  # Segment respondents by voter type.

  mutate(sincere_strategic = case_when(
    (SINCERE_MAX2 == 0 & STRATEGIC_MAX2 == 0) ~ 1,
    (SINCERE_MAX2 == 1 & STRATEGIC_MAX2 == 0) ~ 2,
    (SINCERE_MAX2 == 0 & STRATEGIC_MAX2 == 1) ~ 3,
    (SINCERE_MAX2 == 1 & STRATEGIC_MAX2 == 1) ~ 4,
    )) %>%
  group_by(WA02_c) %>%
  
  # Segment voter type by each age.
  
  mutate(percent = n / sum(n),
         df = "naes08_phone_d",
         age = WA02_c) %>%
  write.csv("/Users/ryan/Google Drive/2020_2021/
            Thesis/Figures/Figure10/age/naes08_phone_d_age.csv")

# Calculate my 4-type voter typology, as segmented by ideology. 

df_final_2 %>%
  inner_join(naes08_phone, by = c("ID" = "RKEY")) %>%
  group_by(SINCERE_MAX2, STRATEGIC_MAX2, MA04_c) %>%
  count() %>%
  
  # Segment respondents by voter type.
  
  mutate(sincere_strategic = case_when(
    (SINCERE_MAX2 == 0 & STRATEGIC_MAX2 == 0) ~ 1,
    (SINCERE_MAX2 == 1 & STRATEGIC_MAX2 == 0) ~ 2,
    (SINCERE_MAX2 == 0 & STRATEGIC_MAX2 == 1) ~ 3,
    (SINCERE_MAX2 == 1 & STRATEGIC_MAX2 == 1) ~ 4,
    )) %>%
  group_by(MA04_c) %>%
  
  # Segment voter type by ideological identification.
  
  mutate(percent = n / sum(n),
         df = "naes08_phone_d",
         ideology = case_when(
           MA04_c == "1" ~ "VERYCONSERVATIVE",
           MA04_c == "2" ~ "SOMEWHATCONSERVATIVE",
           MA04_c == "3" ~ "MODERATE",
           MA04_c == "4" ~ "SOMEWHATLIBERAL",
           MA04_c == "5" ~ "VERYLIBERAL")) %>%
  write.csv("/Users/ryan/Google Drive/2020_2021/Thesis/
            Figures/Figure10/ideology/naes08_phone_d_ideology.csv")

# Calculate my 4-type voter typology, as segmented by strength of party
# identification.

df_final_2 %>%
  inner_join(naes08_phone, by = c("ID" = "RKEY")) %>%
  group_by(SINCERE_MAX2, STRATEGIC_MAX2, MA02_c) %>%
  count() %>%
  
  # Segment respondents by voter type.

  mutate(sincere_strategic = case_when(
    (SINCERE_MAX2 == 0 & STRATEGIC_MAX2 == 0) ~ 1,
    (SINCERE_MAX2 == 1 & STRATEGIC_MAX2 == 0) ~ 2,
    (SINCERE_MAX2 == 0 & STRATEGIC_MAX2 == 1) ~ 3,
    (SINCERE_MAX2 == 1 & STRATEGIC_MAX2 == 1) ~ 4,
    )) %>%
  group_by(MA02_c) %>%
  
  # Segment voter type by strength of party identification.
  
  mutate(percent = n / sum(n),
         df = "naes08_phone_d",
         party_strength = case_when(
           MA02_c == "1" ~ "STRONG",
           MA02_c == "2" ~ "NOTVERYSTRONG")) %>%
  write.csv("/Users/ryan/Google Drive/2020_2021/Thesis/
            Figures/Figure10/party_strength/naes08_phone_d_party_strength.csv")

# Calculate my 4-type voter typology, as segmented by level of political
# interest.

df_final_2 %>%
  inner_join(naes08_phone, by = c("ID" = "RKEY")) %>%
  group_by(SINCERE_MAX2, STRATEGIC_MAX2, KA01_c) %>%
  count() %>%
  
  # Segment respondents by voter type.

  mutate(sincere_strategic = case_when(
    (SINCERE_MAX2 == 0 & STRATEGIC_MAX2 == 0) ~ 1,
    (SINCERE_MAX2 == 1 & STRATEGIC_MAX2 == 0) ~ 2,
    (SINCERE_MAX2 == 0 & STRATEGIC_MAX2 == 1) ~ 3,
    (SINCERE_MAX2 == 1 & STRATEGIC_MAX2 == 1) ~ 4,
    )) %>%
  group_by(KA01_c) %>%
  
  # Segment voter type by strength of political interest.

  mutate(percent = n / sum(n),
         df = "naes08_phone_d",
         political_interest = case_when(
           KA01_c == "1" ~ "VERYCLOSELY",
           KA01_c == "2" ~ "SOMEWHATCLOSELY",
           KA01_c == "3" ~ "NOTTOOCLOSELY",
           KA01_c == "4" ~ "NOTCLOSELYATALL")) %>%
  write.csv("/Users/ryan/Google Drive/2020_2021/Thesis/Figures/Figure10/
            political_interest/naes08_phone_d_political_interest.csv")

# Calculate my 4-type voter typology, as segmented by political efficacy. 

df_final_2 %>%
  inner_join(naes08_phone, by = c("ID" = "RKEY")) %>%
  group_by(SINCERE_MAX2, STRATEGIC_MAX2, MB03_c) %>%
  count() %>%
  
  # Segment respondents by voter type.

  mutate(sincere_strategic = case_when(
    (SINCERE_MAX2 == 0 & STRATEGIC_MAX2 == 0) ~ 1,
    (SINCERE_MAX2 == 1 & STRATEGIC_MAX2 == 0) ~ 2,
    (SINCERE_MAX2 == 0 & STRATEGIC_MAX2 == 1) ~ 3,
    (SINCERE_MAX2 == 1 & STRATEGIC_MAX2 == 1) ~ 4,
    )) %>%
  group_by(MB03_c) %>%
  
  # Segment voter type by level of political efficacy.
  
  mutate(percent = n / sum(n),
         df = "naes08_phone_d",
         efficacy = case_when(
           MB03_c == "1" ~ "STRONGLYAGREE",
           MB03_c == "2" ~ "SOMEWHATAGREE",
           MB03_c == "3" ~ "SOMEWHATDISAGREE",
           MB03_c == "4" ~ "STRONGLYDISAGREE",
           MB03_c == "5" ~ "NEITHER")) %>%
  write.csv("/Users/ryan/Google Drive/2020_2021/Thesis/
            Figures/Figure10/political_efficacy/
            naes08_phone_d_political_efficacy.csv")

```


```{r include=FALSE}

rm(list = ls())

```

